import { useEffect, useRef, useState } from "react";
import { Check, FileDiff, RefreshCw } from "lucide-react";
type Listing = { ok: boolean; error?: string; root?: string; revision?: string; truncated?: boolean; files?: {path:string;status:string}[] };
type Detail = { ok:boolean;error?:string;revision?:string;stagedDiff?:string;unstagedDiff?:string;truncated?:boolean };
type Api = { listChanges(payload:{cwd:string}):Promise<Listing>; readChange(payload:{cwd:string;path:string}):Promise<Detail> };
export function ChangesPanel({cwd}:{cwd?:string}) {
  const api=(window.vibe?.orchestrator as unknown as Api|undefined);
  const [listing,setListing]=useState<Listing>();const [selected,setSelected]=useState("");const [detail,setDetail]=useState<Detail>();const [busy,setBusy]=useState(false);const [reviewed,setReviewed]=useState<string>();const epoch=useRef(0);
  async function refresh(){if(!cwd||!api)return;const token=++epoch.current;setBusy(true);setDetail(undefined);try{const result=await api.listChanges({cwd});if(token===epoch.current){setListing(result);setSelected("");}}catch(e){if(token===epoch.current)setListing({ok:false,error:String(e)});}finally{if(token===epoch.current)setBusy(false);}}
  useEffect(()=>{setListing(undefined);setReviewed(undefined);void refresh();return()=>{epoch.current++;};},[cwd]);
  async function select(file:string){if(!cwd||!api)return;const token=++epoch.current;setSelected(file);setDetail(undefined);setBusy(true);try{const result=await api.readChange({cwd,path:file});if(token===epoch.current){setDetail(result);if(result.revision!==listing?.revision)setReviewed(undefined);}}catch(e){if(token===epoch.current)setDetail({ok:false,error:String(e)});}finally{if(token===epoch.current)setBusy(false);}}
  return <div className="review-workspace"><header><span><FileDiff size={16}/> Working tree</span><button onClick={()=>void refresh()} disabled={busy||!cwd}><RefreshCw size={13}/> Refresh</button>{listing?.revision&&<button title="Marks only your review of this observed change list, not a test result" onClick={()=>setReviewed(listing.revision)} disabled={listing.truncated}><Check size={13}/>{reviewed===listing.revision?"Reviewed snapshot":"Mark reviewed"}</button>}</header>{!cwd?<p className="dock-note">Select a project to inspect changes.</p>:listing?.ok===false?<p className="relay-error">{listing.error}</p>:<div className="review-columns"><nav aria-label="Changed files">{listing?.files?.map(file=><button className={selected===file.path?"active":""} key={file.path} onClick={()=>void select(file.path)}><code>{file.status}</code><span>{file.path}</span></button>)}{listing?.files?.length===0&&<p className="dock-note">Working tree is clean.</p>}</nav><section aria-label="Selected diff">{busy?<p className="dock-note">Reading changes…</p>:detail?.error?<p className="relay-error">{detail.error}</p>:detail?<>{detail.stagedDiff&&<><strong>Staged</strong><pre>{detail.stagedDiff}</pre></>}{detail.unstagedDiff&&<><strong>Working tree</strong><pre>{detail.unstagedDiff}</pre></>}{!detail.stagedDiff&&!detail.unstagedDiff&&<p className="dock-note">No text diff is available.</p>}{detail.truncated&&<p className="dock-note">Preview truncated. Open the file for the complete change.</p>}</>:<p className="dock-note">Select a file. Recorded agent checks remain in the task transcript.</p>}</section></div>}</div>;
}
