export type DocBlock =
  | { type: 'paragraph'; text: string }
  | { type: 'steps'; items: { title: string; text: string }[] }
  | { type: 'list'; items: string[] }
  | { type: 'callout'; tone: 'note' | 'tip' | 'important'; title: string; text: string }
  | { type: 'code'; language: string; code: string }
  | { type: 'table'; headers: string[]; rows: string[][] }
  | { type: 'cards'; items: { title: string; text: string; href: string }[] }
  | { type: 'image'; src: string; alt: string; caption: string };
export type DocSection = { id: string; title: string; blocks: DocBlock[] };
export type DocPage = { slug: string; title: string; description: string; group: string; sections: DocSection[] };
const p = (text: string): DocBlock => ({ type: 'paragraph', text });
const note = (title: string, text: string, tone: 'note' | 'tip' | 'important' = 'note'): DocBlock => ({ type: 'callout', title, text, tone });
const steps = (...items: [string, string][]): DocBlock => ({ type: 'steps', items: items.map(([title,text]) => ({title,text})) });
const list = (...items: string[]): DocBlock => ({ type: 'list', items });
const code = (value: string, language = 'PowerShell'): DocBlock => ({ type: 'code', code: value, language });
const table = (headers: string[], rows: string[][]): DocBlock => ({ type: 'table', headers, rows });
const cards = (...items: [string,string,string][]): DocBlock => ({ type: 'cards', items: items.map(([title,text,href]) => ({title,text,href})) });
const screenshot = (name: string, alt: string, caption: string): DocBlock => ({ type: 'image', src: `/screenshots/${name}.png`, alt, caption });

export const docPages: DocPage[] = [
  { slug: '', title: 'Introduction', description: 'Get to know Lina Terminal, then build your first local workspace.', group: 'Getting started', sections: [
    { id: 'what-is-lina', title: 'What is Lina Terminal?', blocks: [p('Lina Terminal is a Windows desktop workspace for local terminals and coding agents. Open a project, launch the sessions you need, and keep their work side by side in one window.'), p('Use your usual shell, work directly with a coding agent, or pair a planner and an executor in Fusion. The optional Orchestrator connects work across sessions through text and voice.'), note('New here?', 'Start with the quick start guide. You can open a regular terminal before connecting any AI provider.', 'tip'), cards(['Quick start', 'Open a project and run your first session.', '/docs/quick-start'], ['Install Lina', 'Download and launch the Windows desktop app.', '/docs/installation'])] },
    { id: 'three-ways-to-work', title: 'Three ways to work', blocks: [table(['Workflow','What it does','Where to start'], [['Terminal or agent','Work directly in a local shell or your preferred coding CLI.','New session'], ['Fusion or Open Fusion','Use a planner and an executor in one conversation.','New session → Fusion / Open Fusion'], ['Orchestrator','Route instructions and inspect work across your sessions.','Workspace tools → Orchestrator']]), p('These workflows share the same projects and board. You can use a plain terminal for tests while an agent handles a change, then check progress from the Orchestrator.')] },
    { id: 'workspace-tour', title: 'Find your way around', blocks: [screenshot('workspace','Lina Terminal with a project sidebar and four terminal panes.','A demonstration workspace. Your sessions and output will differ.'), list('Sidebar: add projects, switch folders, open Multi mode, or visit the Orchestrator dashboard.', 'New session: choose a terminal or agent for the current project.', 'Session board: arrange, split, resize, and maximize your panes.', 'Workspace tools: open the text Orchestrator, History, Activity, Changes, Files, and Setups.', 'Settings: configure the Orchestrator, voice, and supported provider connections.')] },
    { id: 'before-you-start', title: 'Before you start', blocks: [p('The desktop app runs on Windows x64. Standard terminal panes use your local machine. Agent modes need their own CLI, account, or provider connection; the setup depends on the mode you choose.'), note('Local workspace, connected models', 'Your commands and project files live in the local workspace. AI requests go to the provider you choose. Provider subscriptions and usage charges are separate from Lina plans.'), p('This guide follows the current app controls. Newer modes and settings may differ in an older installed release. Check for updates if an option is missing.')] }
  ] },
  { slug: 'installation', title: 'Install Lina Terminal', description: 'Download the Windows app and get ready to open your first project.', group: 'Getting started', sections: [
    { id: 'requirements', title: 'What you need', blocks: [list('A Windows x64 computer.', 'A local project folder, or a location where you want to create one.', 'For AI features: the account or provider credentials required by your chosen agent.'), p('You do not need to clone the repository, install Node.js, or run a development build to use the packaged desktop app.')] },
    { id: 'install', title: 'Download and install', blocks: [steps(['Download the Windows installer', 'Use the website Download link. Choose the LinaTerminal-Setup file ending in .exe from the latest GitHub release.'], ['Run the installer', 'Follow the installer prompts. Installation is per-user by default.'], ['Open Lina Terminal', 'Launch it from the Start Menu or the desktop shortcut.']), cards(['Download Lina', 'Get the current Windows installer.', '/#download'], ['Open your first project', 'Continue with the quick start.', '/docs/quick-start'])] },
    { id: 'updates', title: 'Keep the app up to date', blocks: [steps(['Check for an update', 'Lina checks at startup. You can also use Check for update in the top bar.'], ['Download when ready', 'Choose Update when a new version is available.'], ['Restart between tasks', 'Let important sessions finish, then choose Restart to apply the update.']), note('You choose when to restart', 'Lina does not automatically download an update or restart active terminal sessions.')] },
    { id: 'existing-workspaces', title: 'Coming from vibeTerminal', blocks: [p('Lina Terminal was previously called vibeTerminal. Existing workspace settings carry over. Some local data folders and repository links keep the earlier name for compatibility; the voice wake phrase is now Hey Lina.')] }
  ] },
  { slug: 'quick-start', title: 'Quick start', description: 'Go from a fresh install to a project with a terminal and a coding agent.', group: 'Getting started', sections: [
    { id: 'open-project', title: '1. Open a project', blocks: [p('Launch Lina Terminal. Select Add project in the sidebar and choose an existing folder. To start a new project instead, select New project and choose its name and location.'), note('Use a project folder', 'Choose the folder that contains the work you want the agent to see. New sessions in a project view start in that folder.', 'tip')] },
    { id: 'start-terminal', title: '2. Start a terminal', blocks: [p('Choose Terminal on the start screen, or open New session → Terminal. A local shell opens inside the board. Run a simple command to confirm the current folder:'), code('Get-Location\nGet-ChildItem'), p('You can now run your normal project commands in this pane, such as your development server or test runner.')] },
    { id: 'add-agent', title: '3. Add an agent', blocks: [steps(['Check the agent is set up', 'For a CLI-backed agent such as Codex or Claude, install and sign in to that CLI first.'], ['Open New session', 'Choose the agent you want to use in this project.'], ['Give it a focused first task', 'Start with a read-only request so you can confirm it is looking at the right project.']), code('Explain how this project is organized.\nIdentify the main entry points and how to run its tests.\nDo not change any files.', 'Example prompt'), cards(['Choose and connect agents', 'Find the setup path for each terminal mode.', '/docs/terminals'])] },
    { id: 'arrange-and-continue', title: '4. Arrange the board and continue', blocks: [p('Drag the pane headers to move sessions. Drag their edges or corners to resize them. Use the pane menu to split, duplicate, or maximize a session.'), p('Keep your shell visible beside the agent. Review its answer, then give a concrete follow-up: name the change, constraints, and the checks you expect it to run.'), cards(['Projects and layouts', 'Make the board fit your workflow.', '/docs/workspaces'], ['Use the Orchestrator', 'Route tasks across sessions.', '/docs/orchestrator'])] }
  ] },
  { slug: 'workspaces', title: 'Projects and layouts', description: 'Organize local folders and arrange sessions without losing their context.', group: 'Workspace', sections: [
    { id: 'project-folders', title: 'Add and switch projects', blocks: [steps(['Add a folder', 'Use Add project to open an existing local folder, or New project to create one.'], ['Select the project', 'Click its sidebar entry to see its sessions. New sessions use that project folder.'], ['Check the folder', 'Use the project name, path, and Git summary to confirm where you are working.']), note('Removing a project', 'Removing a folder from Lina closes its panes and removes it from the workspace. It does not delete the project files. Closing panes still stops their running processes.', 'important')] },
    { id: 'multi-mode', title: 'Use Multi mode', blocks: [p('Choose Multi mode in the sidebar to put sessions from different folders on one board. When you add a pane there, Lina asks which working folder to use.'), p('Use project view when you want one folder in focus. Use Multi mode when you want to monitor or work across several projects together.')] },
    { id: 'arrange-panes', title: 'Arrange, split, and resize', blocks: [table(['Control','How to use it'], [['Move','Drag the pane header to a free position on the board.'], ['Resize','Drag an edge or corner.'], ['Swap','Hold Shift while dropping a pane onto another tile.'], ['Split','Open the pane menu and choose Split right or Split down.'], ['Maximize','Use the maximize control; restore it to return to the board.'], ['Duplicate','Use Duplicate pane to add the same pane type and folder.']]), note('A duplicate is a new session', 'Duplicating a pane copies its type and folder. Use a supported Resume action when you want to continue an existing conversation.')] },
    { id: 'git-context', title: 'Read the Git summary', blocks: [p('For Git repositories, the project view shows branch information and a summary of file changes. Open the branch display to inspect the local branch or worktree information available to Lina.'), p('A folder without a Git repository will not have the same summary. A scan failure or unavailable state is different from a clean working tree.')] }
  ] },
  { slug: 'terminals', title: 'Terminals and agents', description: 'Choose a mode and connect the tools it needs.', group: 'Workspace', sections: [
    { id: 'launch-a-session', title: 'Launch a session', blocks: [steps(['Select a project', 'Choose its sidebar entry, or use Multi mode and select a working folder when prompted.'], ['Choose New session', 'Select Terminal or the coding agent you want to use.'], ['Complete its setup', 'Follow the mode-specific sign-in or provider setup if required.'], ['Send your task', 'Use the terminal or chat composer in the pane, and keep the project scope clear.'])] },
    { id: 'choose-a-mode', title: 'Choose the right mode', blocks: [table(['Mode','What to set up'], [['Terminal','No AI account needed; uses your local shell.'], ['Codex / Claude','Their installed coding CLI and account.'], ['Cursor / Gemini / OpenCode / Kimi / Qwen / Grok Build','The corresponding CLI and its provider setup.'], ['Kimi + CC','The bundled launcher and its account requirements.'], ['Open Codex / Open Claude Code','The shared Models & providers settings.'], ['Codex Web','ChatGPT Web sign-in through the pane menu.'], ['Fusion','Claude/Codex accounts, then planner and executor choices.'], ['Open Fusion','Connect a provider inside the pane, then choose Brain and Executor.']]), cards(['Models and providers', 'Connect Open Codex and Open Claude Code.', '/docs/providers'], ['Fusion', 'Pair two coding agents in one chat.', '/docs/fusion'], ['Open Fusion', 'Choose your own planner and executor models.', '/docs/open-fusion'])] },
    { id: 'check-a-cli', title: 'Check an installed CLI', blocks: [p('If a CLI-backed agent does not start, open a regular terminal and check whether Windows can find its command. Replace codex below with the command for your chosen agent.'), code('Get-Command codex'), p('If the command is not found, finish the provider CLI installation and make it available on PATH. Restart Lina after changing PATH, then try New session again. A dimmed launcher is a detection hint, not a successful installation check.')] },
    { id: 'read-status', title: 'Read session status', blocks: [p('Status shows the activity Lina can observe from the provider. Working, waiting for input, done, and failed states help you decide where to look. Unknown means there is not enough current evidence.'), note('Done is a signal to review', 'An observed completed turn means the agent stopped responding. Read its result and run or inspect the relevant checks before treating the task as complete.')] }
  ] },
  { slug: 'providers', title: 'Models and providers', description: 'Connect a provider once for Open Codex and Open Claude Code.', group: 'Agents and models', sections: [
    { id: 'shared-catalog', title: 'Open the shared catalog', blocks: [p('Open Workspace settings → Models & providers. In current builds, Open Codex and Open Claude Code share this connection and model catalog.'), note('Check your build', 'Older builds may show separate provider settings. Update if the shared Models & providers section is not available.')] },
    { id: 'connect-provider', title: 'Add a provider and models', blocks: [steps(['Add the connection', 'Enter the provider name, API base URL, and key. Use the API prefix required by the provider. Local services may not require a key.'], ['Choose the endpoint format', 'Select the format your provider supports. Available formats include OpenAI Responses, OpenAI Chat Completions, and Anthropic Messages.'], ['Add the models you want', 'Enter model IDs or use model discovery where available. Choose the models you intend to expose in the launcher.'], ['Set model capabilities', 'Use the provider-documented context size and reasoning or image-input support. Select a default model, then save.']), note('Model availability', 'Use IDs and capabilities supplied by your provider. A discovered model does not by itself prove that it supports the tools or input types your task needs.')] },
    { id: 'launch-model', title: 'Launch the same model in either engine', blocks: [p('Open New session, find a configured model, and choose the Open Codex or Open Claude Code engine. Their connections share a catalog, while their terminal sessions and histories stay separate.'), p('After editing model configuration, restart affected panes so they pick up the new settings. Save or finish important work before restarting.'), cards(['Use Open Codex', 'Choose models in the native Codex terminal.', '/docs/open-codex'])] }
  ] },
  { slug: 'open-codex', title: 'Open Codex', description: 'Use the native Codex terminal with your configured providers and models.', group: 'Agents and models', sections: [
    { id: 'before-launch', title: 'Before you launch', blocks: [p('Open Codex is a separate terminal integration with its own provider-backed Codex environment. It uses the normal Codex terminal interface. Configure its connection in Models & providers first.'), cards(['Connect a provider', 'Set up the shared connection and model catalog.', '/docs/providers'])] },
    { id: 'start-open-codex', title: 'Start an Open Codex session', blocks: [steps(['Open New session', 'Select Open Codex, or choose a configured model with the Open Codex engine.'], ['Choose a model', 'Use the models configured in Lina. The session starts with the catalog available at launch.'], ['Work in the terminal', 'Enter your task in the native Codex composer. Follow the terminal prompts for permissions and questions.'])] },
    { id: 'switch-model', title: 'Switch models', blocks: [p('Use the native model picker to choose a model from the session catalog:'), code('/model', 'In the Open Codex terminal'), p('If a model was added after this pane started, restart the pane to load the updated catalog. A removed model may require you to select a replacement before continuing.')] },
    { id: 'separate-conversations', title: 'Keep conversations separate', blocks: [p('Open Codex has its own configuration and conversation history. Changing a provider does not turn an existing session into a standard Codex session. Use the mode-specific resume controls when returning to its work.')] }
  ] },
  { slug: 'codex-web', title: 'Codex Web', description: 'Connect a ChatGPT Web account to the Codex terminal in Lina.', group: 'Agents and models', sections: [
    { id: 'connect-account', title: 'Connect your Web account', blocks: [steps(['Open New session → Codex Web', 'Lina reuses a valid cached Web login. If one is needed, complete ChatGPT sign-in in the browser window opened by the pane.'], ['Keep the sign-in window open', 'Wait until Lina confirms it saved the session. A separate native Codex login is not required by this Web flow.'], ['Choose an available model', 'The account model catalog loads automatically. Use /model inside the terminal to choose a supported model.']), note('Availability depends on your build and account', 'Codex Web is a newer integration. The models and tool access available to it depend on your installed build, account, and completed setup.')] },
    { id: 'tools-and-history', title: 'Enable coding tools and resume work', blocks: [p('Browser-only mode supports text turns without a local tool bridge. For coding access, open the pane menu → Codex Web tools setup and complete the requested tunnel and connector setup. Wait for verification before asking it to operate on local files.'), p('The pane uses native Codex conversation history. Use the native resume picker to continue a saved conversation:'), code('/resume', 'In the Codex Web terminal'), note('Review tool readiness', 'A working model picker or text reply does not mean that local coding tools are connected. Resolve any tools-setup message in the terminal first.')] },
    { id: 'account-controls', title: 'Manage sign-in', blocks: [p('Use ChatGPT Web sign in or ChatGPT Web sign out in the pane menu. These controls manage the Web connection. Signing out keeps local conversation history.'), p('If authentication expires, sign in again. After a connection error, check the terminal before resending a request so you do not accidentally duplicate work.')] }
  ] },
  { slug: 'fusion', title: 'Fusion', description: 'Use a planner and an executor together in a single coding conversation.', group: 'Agents and models', sections: [
    { id: 'start-fusion', title: 'Start a Fusion pane', blocks: [steps(['Set up the accounts you will use', 'Fusion uses the Claude and Codex agent families. Make sure the relevant account sign-ins are ready.'], ['Open New session → Fusion', 'Choose the project folder where you want the task to run.'], ['Review the role choices', 'The composer shows the planner and executor. Click either model label to choose its family and model.']), p('The classic pairing is Claude planning and reviewing with Codex building and testing. Current builds also let you choose the family for each role.')] },
    { id: 'give-fusion-a-task', title: 'Give the pair a task', blocks: [code('Add validation to the settings form.\nKeep the existing layout and error messages.\nRun the relevant tests and summarize the changes.', 'Example prompt'), p('The planner works out the approach and delegates changes to the executor. Follow its progress in the same chat. Answer permission requests or questions when they appear, then review the result.'), note('Keep the scope clear', 'Name the files or behavior that matter, say what should stay unchanged, and describe how to verify the result.', 'tip')] },
    { id: 'model-and-chat-controls', title: 'Use model and conversation controls', blocks: [table(['Action','How to find it'], [['Planner model','Click the planner label or use /planner-model.'], ['Executor model','Click the executor label or use /executor-model.'], ['Available commands','Use /help in the composer.'], ['Saved chat','Use /resume to open the saved-chat picker.'], ['Plan / Auto','Use the composer mode control; Shift+Tab switches where shown.']]), p('A planner change can restart the pane. Changing families can begin a new conversation, so check the selected role and session before continuing.') ] }
  ] },
  { slug: 'open-fusion', title: 'Open Fusion', description: 'Choose a Brain and Executor from your own connected providers.', group: 'Agents and models', sections: [
    { id: 'connect-and-choose', title: 'Connect and choose your pair', blocks: [steps(['Open New session → Open Fusion', 'Start in the project folder for your task.'], ['Connect a provider', 'Choose Connect a provider or use /connect. Follow the API-key or browser sign-in flow offered by that provider.'], ['Pick a Brain', 'Choose the model that will plan and review the work.'], ['Pick an Executor', 'Choose the model that will make changes and run checks.']), note('No default pair', 'Open Fusion does not silently choose your two models. Connect a provider and set both roles before starting the task.'), screenshot('open-fusion','Open Fusion inside Lina with provider connection and model selection controls.','Open Fusion first-run setup in a demonstration workspace.')] },
    { id: 'work-with-pair', title: 'Work with the pair', blocks: [p('Describe the goal in the chat composer. The Brain directs the Executor and reviews the result. Follow progress, respond to permission prompts in the pane, and send a follow-up when you need to steer the task.'), p('Use the model labels in the composer to review or change role choices. Open /help for the commands supported by your build.')] },
    { id: 'provider-troubles', title: 'If a model or provider is missing', blocks: [list('Check that the provider connection is complete and valid.', 'Confirm the selected provider actually offers the model on your account.', 'Refresh the catalog or retry a failed catalog request when the pane offers that action.', 'Set both Brain and Executor again if a previously chosen model is no longer available.'), p('Open Fusion keeps its own provider configuration inside Lina. Connecting a provider there does not automatically configure your global OpenCode installation.')] }
  ] },
  { slug: 'orchestrator', title: 'Use the Orchestrator', description: 'Give instructions, route tasks, and inspect work across your projects.', group: 'Orchestrator and voice', sections: [
    { id: 'connect-orchestrator', title: 'Connect the assistant', blocks: [steps(['Open Workspace settings', 'Select the Orchestrator & voice section.'], ['Add your OpenRouter key and model', 'Choose an assistant model suitable for tool use. Browse the model list or enter the model ID.'], ['Save and enable', 'Enable Orchestrator to save and validate the current settings. This activation flow can request microphone access. Use the text conversation when you want to type.']), note('Keep account costs in mind', 'Orchestrator requests use your OpenRouter account. You can set a spending limit in Advanced settings.'), cards(['Configure voice', 'Choose push-to-talk or optional Hey Lina activation.', '/docs/voice'])] },
    { id: 'send-text', title: 'Send a text instruction', blocks: [steps(['Open Workspace tools → Orchestrator', 'Use the workspace-tools control in the top bar to open the text conversation.'], ['Choose the target', 'Leave Auto-assign selected to let Lina choose a suitable session. Select a named session when you want to address it directly.'], ['Enter the task', 'Include the project and the result you want. Press Enter to send; Shift+Enter adds a new line.']), code('Have Codex review the latest changes in the website project.\nReport the findings before changing any files.', 'Example instruction'), p('In a project view, Auto-assign uses that project context. A related follow-up can return to its existing task owner; independent work can use a separate conversation.')] },
    { id: 'follow-progress', title: 'Follow activity and results', blocks: [p('Open Orchestrator in the sidebar for the session dashboard. Select a session to return to its pane. Use Work history to browse observed finished, failed, or interrupted turns.'), screenshot('orchestrator','The Orchestrator dashboard showing project names, providers, and activity states.','Demonstration sessions in the live-session dashboard.'), note('Sending and finishing are different', 'A delivered instruction does not mean the agent completed the task. Read the task response and review the result in its terminal.')] },
    { id: 'questions-and-followups', title: 'Answer questions and continue', blocks: [p('Use Reply on the question you want to answer. Keep the answer associated with that request when several agents are waiting. You can send another instruction while other tasks run.'), code('What is Claude working on in the API project?\nTell it to add tests for the changes.\nFind my previous conversation about the login screen.', 'More example instructions'), p('For a new topic, name the project or target again. For related work, give a clear follow-up so Lina can keep it with the right conversation.')] },
    { id: 'stop-or-steer', title: 'Stop or steer a request', blocks: [p('Use the request controls in the text conversation to stop or redirect work. Read the scope of a stop action before choosing it; Stop all applies across active Orchestrator requests.'), p('Your terminal panes remain available for direct input. A voice dismissal, hiding the microphone, and interrupting an agent are different actions. Use the voice guide for those controls.')] }
  ] },
  { slug: 'voice', title: 'Voice and Hey Lina', description: 'Speak to your workspace, answer agent questions, and control listening.', group: 'Orchestrator and voice', sections: [
    { id: 'set-up-voice', title: 'Set up voice', blocks: [steps(['Connect the Orchestrator', 'Add your OpenRouter key and assistant model in Workspace settings → Orchestrator & voice.'], ['Enable and allow the microphone', 'Enable Orchestrator and respond to Lina’s microphone request. Windows microphone privacy settings must also allow access.'], ['Choose preferences', 'Use Advanced settings to choose your microphone and voice. Preview the voice after saving a valid configuration.']), screenshot('voice-settings','Lina Orchestrator and voice settings with empty account fields.','Settings in the desktop app. Enter your own credentials only inside Lina.')] },
    { id: 'push-to-talk', title: 'Hold Space to talk', blocks: [steps(['Move focus out of terminal input', 'Space remains a normal key inside terminal panes and text fields. Click a non-input part of the workspace before using the voice shortcut.'], ['Hold Space and speak', 'A short listening cue marks the start of recording.'], ['Release to send', 'Lina processes the request and speaks its response.']), p('You can also hold the microphone button with the mouse. A very short tap is discarded. During an automatic recording, the microphone becomes a Send control so you can finish the turn yourself.')] },
    { id: 'hands-free', title: 'Enable Hey Lina', blocks: [p('In Orchestrator & voice settings, check Hands-free voice – Hey Lina and choose Save changes. Wait for it to become ready, then say Hey Lina followed by the request.'), code('Hey Lina, what is Codex working on?\nHey Lina, open the website project.', 'Example voice requests'), p('When Lina asks a question, it opens an answer window. Answer naturally without repeating the wake phrase. If automatic listening is unavailable, hold Space to answer.')] },
    { id: 'interrupt-and-mute', title: 'Interrupt, dismiss, or mute', blocks: [table(['What you want','What to do'], [['Interrupt a spoken reply','Say Hey Lina, or hold Space during playback, then give your next request.'], ['Dismiss this voice exchange','Say never mind, or click the microphone indicator’s X.'], ['Stop microphone capture','Use Mute / disable voice.'], ['Hide only the indicator','Use Hide microphone · keep listening. This does not mute it.'], ['Restore the indicator','Use Show microphone in the top bar.']]), note('Dismissing voice does not cancel terminal work', 'Say never mind to end the current voice exchange. Use the task or terminal controls if you intend to stop the agent’s work.', 'important')] },
    { id: 'local-and-cloud', title: 'Know what runs locally', blocks: [p('Wake detection and speech timing run locally. Completed recordings, assistant requests, and generated speech use OpenRouter and the selected services. Recognition depends on your microphone and surroundings.'), p('Hands-free is optional. Closing Lina stops listening; startup listening stays off unless you enable it in settings.')] }
  ] },
  { slug: 'history-and-setups', title: 'History and saved setups', description: 'Find conversations, review finished work, and reuse an arrangement of sessions.', group: 'Workspace', sections: [
    { id: 'saved-conversations', title: 'Find a saved conversation', blocks: [steps(['Open Workspace tools → History', 'Browse conversations for supported providers and known project folders.'], ['Find the right thread', 'Use the project, provider, title, and available history details to identify it.'], ['Resume deliberately', 'Choose the supported resume action for that conversation.']), p('Some panes also offer Resume last chat in their menu when a saved conversation is available. Fusion uses /resume; Codex Web also uses the native /resume command.')] },
    { id: 'work-history', title: 'Review work history', blocks: [p('Open Orchestrator → Work history. Choose All projects or a specific project, then search by work title, agent, provider, or result details.'), p('These are observed agent turns. An entry can remain readable after a terminal closes. Older work or providers without sufficient activity information may not have a record.'), note('History is a record, not a running task', 'Opening a history entry does not restart work. Review its result and deliberately resume or send a new instruction when you want to continue.')] },
    { id: 'save-setup', title: 'Save and launch a setup', blocks: [steps(['Arrange the sessions you want', 'Open the project folders and pane types that belong in the setup.'], ['Open Workspace tools → Setups', 'Save the arrangement under a name you will recognize.'], ['Launch it when needed', 'Choose the saved setup to start a fresh arrangement. Review any staged drafts before sending.']), p('You can also ask the Orchestrator: Save this setup as Frontend work. Then ask: Launch setup Frontend work.'), note('A setup is a recipe', 'Saved setups use fresh session identities. They do not restore approvals, credentials, or the authority of an old request.')] },
    { id: 'handoffs', title: 'Pass context to another session', blocks: [p('Use a handoff to stage your instruction with selected output and file references. Choose the source and destination carefully, review the staged content, and send it when ready.'), p('Staging a handoff does not send bytes to a terminal. Check the destination’s project and conversation before submitting.')] }
  ] },
  { slug: 'controls', title: 'Keyboard and pane controls', description: 'A practical reference for the controls used throughout this guide.', group: 'Reference', sections: [
    { id: 'workspace-controls', title: 'Workspace controls', blocks: [table(['Control','Action'], [['Drag a pane header','Move the pane.'], ['Drag an edge or corner','Resize the pane.'], ['Shift + drop on another tile','Swap tiles.'], ['Pane menu → Split right / Split down','Create a split layout.'], ['Pane maximize / restore','Focus a pane, then return to the board.'], ['Pane menu → Duplicate pane','Create a new pane of the same type and folder.'], ['Pane menu → Restart terminal','Stop and relaunch the pane’s process.'], ['Right-click inside a terminal','Open Copy and Paste actions.']]), note('Before closing or restarting', 'These actions stop the current process. Save your work and check whether a supported conversation resume is available.', 'important')] },
    { id: 'conversation-controls', title: 'Conversation controls', blocks: [table(['Where','Control','Action'], [['Orchestrator composer','Enter','Send the instruction.'], ['Orchestrator composer','Shift + Enter','Insert a new line.'], ['Fusion','/help','Open available commands.'], ['Fusion','/resume','Choose a saved chat.'], ['Codex / Open Codex / Codex Web','/model','Open the native model picker.'], ['Codex Web','/resume','Resume native conversation history.']]), p('Individual provider CLIs can have their own shortcuts and keymaps. Use the commands shown inside that terminal when they differ from this reference.')] },
    { id: 'voice-controls', title: 'Voice controls', blocks: [table(['Control','Action'], [['Hold Space outside terminals/text fields','Record a voice request; release to send.'], ['Hold microphone button','Start a manual voice recording.'], ['Hey Lina','Start a hands-free request when enabled and ready.'], ['Hey Lina / Space during speech','Interrupt playback and start your next request.'], ['Never mind / indicator X','Dismiss the current voice exchange.'], ['Mute','Turn off the microphone.']])] }
  ] },
  { slug: 'troubleshooting', title: 'Troubleshooting', description: 'Resolve common launch, connection, voice, and workflow issues.', group: 'Reference', sections: [
    { id: 'agent-wont-start', title: 'An agent will not start', blocks: [steps(['Check the mode’s setup', 'A regular CLI mode needs the provider CLI installed. Open Codex, Codex Web, Fusion, and Open Fusion have their own setup paths.'], ['Check the working folder', 'Make sure the project still exists and the terminal is using the intended folder.'], ['Read the terminal error', 'For CLI-backed modes, test the command in a plain terminal. After changing PATH, restart Lina.']), code('Get-Command codex', 'PowerShell example')] },
    { id: 'provider-or-model-error', title: 'A provider or model is unavailable', blocks: [list('Check the API base URL, key, endpoint format, and model ID in the relevant settings.', 'Confirm your account has access to that model.', 'Retry or refresh the catalog when the pane offers it.', 'Restart affected panes after changing the shared model catalog.', 'For Open Fusion, set both Brain and Executor; for Codex Web, resolve sign-in and tools setup separately.') ] },
    { id: 'voice-not-listening', title: 'Voice is not listening', blocks: [list('Confirm the Orchestrator connection is valid and the microphone is enabled.', 'Check Lina’s microphone permission and Windows microphone privacy settings.', 'For Space push-to-talk, move focus outside a terminal or text field.', 'For Hey Lina, enable hands-free, save, and wait for the ready state.', 'If hands-free is unavailable, use Space or the microphone button.'), p('A hidden microphone indicator can still be listening. Use Show microphone to restore it, and use Mute when you want listening to stop.')] },
    { id: 'request-not-finished', title: 'An instruction was sent, but the task is not finished', blocks: [p('Check the target terminal and the request’s activity. Delivery, queued input, an agent running, and a completed result are separate states. The agent may be busy, waiting for permission, or asking a question.'), p('Answer the specific pending question or inspect the error before resending. If delivery is uncertain, a second submission can duplicate work.')] },
    { id: 'missing-history', title: 'A conversation or result is missing', blocks: [p('Check the project and provider filters in History. Conversation support varies by provider. The Orchestrator work table only contains turns it could observe, so older work and incomplete activity signals may be absent.'), p('Use the mode’s own saved-chat or native resume controls when available. A closed terminal may still have readable history even when its live-session link is no longer available.')] },
    { id: 'get-help', title: 'Still need help?', blocks: [p('When reporting a problem, include the Lina version, Windows version, pane type, the action you took, and the visible error. Share a small reproduction where possible, and remove credentials or private project details from logs and screenshots.'), cards(['Open the issue tracker', 'Search existing reports or describe the problem.', 'https://github.com/luigicarter/VibeTerminal/issues'], ['Check for updates', 'Review the latest available release.', '/#download'])] }
  ] }
];

export const docGroups = ['Getting started', 'Workspace', 'Agents and models', 'Orchestrator and voice', 'Reference'];
export const docHref = (slug: string) => slug ? `/docs/${slug}` : '/docs';
export function blockText(block: DocBlock): string {
  if (block.type === 'paragraph' || block.type === 'callout') return ('title' in block ? block.title + ' ' : '') + block.text;
  if (block.type === 'steps') return block.items.map(item => item.title + ' ' + item.text).join(' ');
  if (block.type === 'list') return block.items.join(' ');
  if (block.type === 'code') return block.code;
  if (block.type === 'table') return [...block.headers, ...block.rows.flat()].join(' ');
  if (block.type === 'cards') return block.items.map(item => item.title + ' ' + item.text).join(' ');
  return block.alt + ' ' + block.caption;
}
export type DocSearchResult = { page: DocPage; section?: DocSection; excerpt: string; score: number };
export function searchDocs(query: string): DocSearchResult[] {
  const tokens = query.trim().toLowerCase().split(/\s+/).filter(Boolean);
  if (!tokens.length) return [];
  return docPages.flatMap(page => {
    const sections = page.sections.map(section => ({ section, text: section.title + ' ' + section.blocks.map(blockText).join(' ') }));
    const all = [page.title, page.description, ...sections.map(item => item.text)].join(' ').toLowerCase();
    if (!tokens.every(token => all.includes(token))) return [];
    const match = sections.find(item => tokens.every(token => item.text.toLowerCase().includes(token)));
    const text = match?.text || page.description;
    const score = tokens.reduce((sum,token) => sum + (page.title.toLowerCase().includes(token) ? 10 : 0) + (match?.section.title.toLowerCase().includes(token) ? 3 : 0), 0);
    return [{ page, section: match?.section, excerpt: text.length > 145 ? text.slice(0,145).trimEnd() + '…' : text, score }];
  }).sort((a,b) => b.score - a.score);
}
