import { ArrowLeft, ArrowUpRight, AudioLines, Check, Download, Keyboard, MessageCircle, Mic, Shield, Volume2 } from "lucide-react";
import { VoiceExperience } from "../components/VoiceExperience";

export const VoiceSection = () => <div className="product-page product-page--voice section-shell" id="top">
  <a className="breadcrumb" href="/"><ArrowLeft size={15} /> Back to Lina Terminal</a>
  <section className="product-hero"><p className="eyebrow"><span>A CONVERSATION WITH YOUR WORKSPACE</span> / VOICE</p><h1>Think out loud.<br /><span>Keep building.</span></h1><p>“Hey Lina” brings your voice into the workflow. Delegate a task, check an agent, or answer a question while your terminals keep working.</p><div className="hero__actions"><a className="button button--primary" href="/#download"><Download size={17} />Get Lina Terminal</a><a className="button button--quiet" href="#voice-demo">See the voice workflow <ArrowUpRight size={16} /></a></div></section>
  <section className="product-section" id="voice-demo"><VoiceExperience /></section>
  <section className="product-section"><div className="section-heading"><p className="eyebrow">TWO WAYS TO START</p><h2>A key when you want it.<br /><span>A word when you don't.</span></h2></div><div className="voice-modes">
    <article><Keyboard size={25} strokeWidth={1.4} /><div className="voice-key"><kbd>space</kbd><span>Hold to talk · release to send</span></div><h3>Push to talk.</h3><p>Hold Space while a terminal or text field isn't focused. Speak your request, then release. You can also hold the microphone button in the app.</p></article>
    <article><Mic size={25} strokeWidth={1.4} /><div className="voice-key"><span className="wake-word">“Hey Lina”</span><span>Say it. Then say what you need.</span></div><h3>Go hands-free.</h3><p>Enable optional hands-free voice, say “Hey Lina,” and give your request. Local wake detection runs on your CPU, with no voice training or separate account.</p></article>
  </div></section>
  <section className="product-section"><div className="section-heading"><p className="eyebrow">KEEP THE CONVERSATION NATURAL</p><h2>A little less back-and-forth.</h2></div><div className="capability-grid voice-capabilities">
    <article><MessageCircle size={23} /><h3>Just answer.</h3><p>When Lina asks a question, it opens an answer window. Reply naturally, or say “the second one” for an explicit choice.</p></article>
    <article><Volume2 size={23} /><h3>Cut in when you need to.</h3><p>Say “Hey Lina” or hold Space during a spoken reply to interrupt playback and give your next instruction.</p></article>
    <article><AudioLines size={23} /><h3>Know when it's listening.</h3><p>A short cue marks the start of capture. The microphone changes with listening, understanding, and speaking states.</p></article>
  </div></section>
  <section className="voice-screen-section product-section"><figure className="product-shot"><a href="/screenshots/voice-settings.png" target="_blank" rel="noreferrer"><img src="/screenshots/voice-settings.png" width="1440" height="920" loading="lazy" alt="Lina Terminal's Orchestrator and voice settings, showing assistant configuration, hands-free voice, and advanced controls." /></a><figcaption><span>Orchestrator & voice settings · app screenshot</span><a href="/screenshots/voice-settings.png" target="_blank" rel="noreferrer">Full size <ArrowUpRight size={14} /></a></figcaption></figure><div className="section-heading"><p className="eyebrow">SET IT UP YOUR WAY</p><h2>Your voice.<br /><span>Your preferences.</span></h2><p>Choose your assistant model, microphone, and spoken voice in Workspace settings → Orchestrator & voice. Preview your voice and set spending limits in Advanced.</p><a className="text-link" href="/orchestrator#orchestrator-setup">Set up the Orchestrator <ArrowUpRight size={16} /></a></div></section>
  <section className="product-details"><div><p className="eyebrow"><Shield size={15} /> CLEAR CONTROLS</p><h2>Speak when you want.<br /><span>Pause when you need.</span></h2><p>Hands-free voice is optional. Enable microphone access in Lina when you're ready, and turn it off from the microphone controls.</p></div><ul className="check-list"><li><Check size={18} />Say “never mind” to dismiss the voice exchange.</li><li><Check size={18} />Muting turns off the microphone.</li><li><Check size={18} />Dismissing a reply leaves terminal work running.</li><li><Check size={18} />Closing Lina stops listening.</li></ul></section>
  <p className="product-note">Wake-word detection and speech timing run locally. Completed recordings, assistant requests, and generated speech use OpenRouter and your selected services. Provider charges may apply. Recognition depends on your microphone and surroundings.</p>
  <div className="product-crosslink"><div><p>Voice is one way in. The Orchestrator connects the rest.</p><h2>Meet the workspace behind the voice.</h2></div><a className="button button--secondary" href="/orchestrator">Explore Orchestrator <ArrowUpRight size={16} /></a></div>
</div>;
