"use strict";
const test = require("node:test"), assert = require("node:assert/strict");
const { EventEmitter } = require("node:events");
const fs = require("node:fs"), os = require("node:os"), path = require("node:path");
const { createSessionDirectory, installOrchestrator } = require("../../backend/orchestratorIntegration.cjs");
const { createSettings } = require("../../backend/orchestratorSettings.cjs");
test("explicit session-only key works without secure storage and never persists",t=>{
  const root=fs.mkdtempSync(path.join(os.tmpdir(),"vibe-orchestrator-integration-"));
  t.after(()=>{assert(path.resolve(root).startsWith(path.join(os.tmpdir(),"vibe-orchestrator-integration-")));fs.rmSync(root,{recursive:true,force:true});});
  const store=createSettings({userDataPath:root,secureStorage:{isEncryptionAvailable:()=>false}});
  store.configure({apiKey:"ephemeral-test-key",sessionOnly:true});assert.equal(store.getKey(),"ephemeral-test-key");
  assert(!fs.readFileSync(path.join(root,"orchestrator-settings.json"),"utf8").includes("ephemeral-test-key"));
  assert.equal(createSettings({userDataPath:root}).getKey(),"");
});
test("directory retains generations and streams text without splitting words", () => {
  let now = 100; const d = createSessionDirectory({ getRuntime: () => ({ listSnapshots: () => [] }), now: () => now++ });
  const first = d.outgoing("fusion", { type: "start", payload: { id: "f", cwd: "C:/project" } });
  const generation = first.payload.generation;
  d.ingest("fusion", { id: "f", generation, type: "assistant-text", delta: "hel" });
  d.ingest("fusion", { id: "f", generation, type: "assistant-text", delta: "lo" });
  assert.equal(d.readChat({id:"f",generation}).text,"hello");
  d.outgoing("fusion", {type:"stop",payload:{id:"f"}});
  const next = d.outgoing("fusion",{type:"start",payload:{id:"f",cwd:"C:/project"}});
  d.ingest("fusion",{id:"f",generation,type:"closed"});
  assert.equal(d.get("f").generation,next.payload.generation);
  assert.equal(d.get("f").status,"starting");
  assert.equal(d.outgoing("fusion",{type:"input",payload:{id:"f",generation}}).payload.generation,generation);
});
test("real integration bridges UI and strict PTY acknowledgment without cloud or duplicate effects",async t=>{
  const root=fs.mkdtempSync(path.join(os.tmpdir(),"vibe-orchestrator-integration-"));
  const docs=path.join(root,"Documents"),data=path.join(root,"data");fs.mkdirSync(docs);fs.mkdirSync(data);
  t.after(()=>{ assert(path.resolve(root).startsWith(path.join(os.tmpdir(),"vibe-orchestrator-integration-")));fs.rmSync(root,{recursive:true,force:true}); });
  const ipc=new EventEmitter();ipc.handlers=new Map();ipc.handle=(key,fn)=>ipc.handlers.set(key,fn);
  const app=new EventEmitter();app.getPath=key=>key==="documents"?docs:data;app.isPackaged=false;
  let integration; const uiActions=[],opened=[],sent=[];
  const main=new EventEmitter();main.isDestroyed=()=>false;main.webContents=new EventEmitter();
  main.webContents.send=(channel,p)=>{
    if(channel!=="orchestrator:ui-action")return;
    uiActions.push(p);
    const result=p.kind==="inventory"?{ok:true,projectPaths:[docs],sessions:[{id:"term",kind:"terminal",name:"Terminal",cwd:docs,launchToken:1,started:true}]}:p.kind==="stage_draft"?{ok:true,status:"staged"}:{ok:true,status:"completed"};
    queueMicrotask(()=>ipc.emit("orchestrator:ui-result",{sender:main.webContents},{id:p.id,result}));
  };
  const BrowserWindow={getAllWindows:()=>[main]};
  const snapshot={id:"term",generation:"g1",launchToken:1,provider:"terminal",cwd:docs,turnState:"idle",processState:"running",agentProcessState:"unknown",revision:1};
  const sendPty=m=>{sent.push(m);queueMicrotask(()=>integration.incoming("terminal",{id:m.payload.id,generation:m.payload.generation,type:"action-result",actionId:m.payload.actionId,ok:true,status:"written"}));return true;};
  integration=installOrchestrator({app,BrowserWindow,ipcMain:ipc,screen:{},shell:{openPath:async p=>{opened.push(p);return "";}},safeStorage:{isEncryptionAvailable:()=>false},getMainWindow:()=>main,getRuntime:()=>({listSnapshots:()=>[snapshot]}),sendPty,sendFusion:()=>false,sendOpenFusion:()=>false,getTelemetry:()=>({}),getChanges:()=>({})});
  t.after(()=>integration.dispose());
  const invoke=(name,p={})=>ipc.handlers.get(name)({sender:main.webContents},p);
  await integration.refreshInventory();
  const result=await invoke("orchestrator:dispatch",{kind:"send_prompt",target:{id:"term",generation:"g1"},text:"echo test"});
  assert.equal(result.ok,true);assert.equal(result.status,"written");assert.equal(sent.length,1);assert.equal(sent[0].payload.data,"echo test\r");
  const stale=await invoke("orchestrator:dispatch",{kind:"send_prompt",target:{id:"term",generation:"old"},text:"oops"});
  assert.equal(stale.ok,false);assert.equal(sent.length,1);
  const exe=path.join(docs,"fake.exe");fs.writeFileSync(exe,"fixture");
  assert.equal((await invoke("orchestrator:dispatch",{kind:"open_folder",path:exe})).ok,false);
  assert.equal(opened.length,0);
  const outside=path.join(root,"outside.txt");fs.writeFileSync(outside,"fixture");
  assert.equal((await invoke("orchestrator:dispatch",{kind:"open_file",path:outside})).ok,false);
  const doc=path.join(docs,"notes.txt");fs.writeFileSync(doc,"fixture");
  assert.equal((await invoke("orchestrator:dispatch",{kind:"open_file",path:doc})).ok,true);
  assert.deepEqual(opened,[doc]);
  const stranger=await ipc.handlers.get("orchestrator:dispatch")({sender:{}},{kind:"close",targetId:"term"});assert.equal(stranger.ok,false);
  assert.equal((await invoke("voice:listening",{enabled:true})).ok,false);
});
